import assert from 'node:assert/strict';
import { connect,sleep } from './cdp.js';
const c=await connect(),ev=c.evaluate;
const terrain=async()=>{for(let i=0;i<200;i++){if(await ev('v.chunks.size>=9&&!v.inflight&&!v.queue.length&&!v.ready.length'))return;await sleep(100);}throw Error('Terrain did not settle');};
try{
  await c.send('Emulation.setTouchEmulationEnabled',{enabled:false});await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await c.send('Page.navigate',{url:'http://localhost:3001/'});await sleep(650);
  await ev(`(async()=>{const m=await import('./src/main.js?v=33');window.g=m.game;window.v=m.renderer;window.ui=m.ui;g.start('adventure',true);g.pos={x:.5,y:7,z:9.5};g.yaw=0;g.pitch=0;g.mobs=[];g.pause('inventory');ui.render();})()`);await terrain();
  assert.equal(await ev('document.querySelectorAll("#world canvas").length'),1);
  await c.click('[data-discover=glider]');assert.equal(await ev('document.querySelectorAll(".item-card").length'),6);await c.click('[data-inspect=hang_glider]');assert.ok(await ev("document.querySelector('.item-detail').textContent.includes('Show crafting recipe')"));await c.screenshot('horizon-glider-catalogue');await c.click('[data-recipe=hang_glider]');assert.equal(await ev('g.screen'),'craft');assert.ok(await ev('!!document.querySelector("[data-craft=hang_glider]")'));
  await c.click('[data-action=inventory]');await c.click('[data-discover=cotton]');assert.equal(await ev('document.querySelectorAll(".item-card").length'),3);await c.click('[data-inspect=cotton_seeds]');await c.click('[data-equip=cotton_seeds]');assert.equal(await ev('g.held'),'cotton_seeds');await c.screenshot('horizon-cotton');
  await ev(`g.resume();ui.render();g.pos={x:.5,y:7,z:9.5};g.yaw=0;g.pitch=-.95;g.world.set(0,6,8,'farmland');g.world.set(0,7,8,null)`);await sleep(200);
  await c.send('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyE',key:'e'});await c.send('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyE',key:'e'});assert.equal(await ev("g.world.get(0,7,8)"),'cotton_sprout');await ev('g.state.elapsed+=101');await sleep(1200);assert.equal(await ev("g.world.get(0,7,8)"),'cotton_crop');await c.send('Input.dispatchKeyEvent',{type:'keyDown',code:'KeyE',key:'e'});await c.send('Input.dispatchKeyEvent',{type:'keyUp',code:'KeyE',key:'e'});assert.equal(await ev('g.state.inv.cotton'),3);
  // Fix the target's position to isolate the real mouse hold from wandering AI.
  await ev(`g.equip('wood_pickaxe');g.pos={x:.5,y:7,z:9.5};g.yaw=0;g.pitch=Math.atan2(.54-1.58,2.5);g.world.set(0,7,8,'flower_red');window.originalMobs=g.updateMobs;g.updateMobs=()=>{};window.pig=g.spawnMob(.5,7,'pig',7);`);await sleep(200);
  assert.ok(await ev("document.querySelector('#target').textContent.includes('Pig')"));await c.send('Input.dispatchMouseEvent',{type:'mousePressed',x:720,y:500,button:'left',clickCount:1});await sleep(900);assert.ok(await ev('pig.hp')<=6);assert.equal(await ev('g.state.stats.mined'),0);await c.screenshot('horizon-hunting');await sleep(1500);await c.send('Input.dispatchMouseEvent',{type:'mouseReleased',x:720,y:500,button:'left',clickCount:1});assert.equal(await ev('g.mobs.includes(pig)'),false);assert.ok(await ev("g.state.drops.some(d=>d.item==='raw_pork')"));await ev('g.updateMobs=originalMobs');
  await ev(`g.world.set(1,7,9,'bench');g.add('cloth',9);g.add('wood',12);g.add('leather',3);g.pause('craft');ui.search='Canvas hang glider';ui.filter='All';ui.render()`);await c.click('[data-craft=hang_glider]');assert.equal(await ev('g.state.inv.hang_glider'),1);await c.click('[data-action=inventory]');await c.click('[data-discover=glider]');await c.click('[data-inspect=hang_glider]');await c.click('[data-equip=hang_glider]');assert.equal(await ev('g.state.glider'),'hang_glider');
  const saved=await ev('g.state.animals.length');await ev('g.save()');await c.send('Page.reload');await sleep(700);await ev(`(async()=>{const m=await import('./src/main.js?v=33');window.g=m.game;window.v=m.renderer;window.ui=m.ui;})()`);assert.equal(await ev('g.state.glider'),'hang_glider');assert.equal(await ev('g.state.inv.cotton'),3);assert.equal(await ev('document.querySelectorAll("#world canvas").length'),1);
  await ev(`g.start('creative',true);g.pause('inventory');ui.catalogue=false;ui.search='';ui.filter='Gear';ui.render();document.querySelector('#toasts').replaceChildren()`);await c.screenshot('horizon-item-art');
  await ev(`g.resume();ui.render();g.flying=true;g.pos={x:-170.5,y:g.world.height(-170,-80)+5,z:-70.5};g.yaw=0;g.pitch=-.18;g.state.time=100;g.equip('diamond_axe');document.querySelector('#toasts').replaceChildren()`);await terrain();await c.screenshot('horizon-woodland');
  await ev(`g.pos={x:65.5,y:g.world.height(65,-205)+13,z:-205.5};g.yaw=.5;g.pitch=-.35;g.equip('gold_pickaxe')`);await terrain();await c.screenshot('horizon-alpine');
  const timing=await ev(`new Promise(resolve=>{let previous=performance.now(),frames=[];const sample=t=>{frames.push(t-previous);previous=t;if(frames.length<90)requestAnimationFrame(sample);else{frames.sort((a,b)=>a-b);resolve({median:frames[45],p95:frames[85],drawCalls:v.renderer.info.render.calls,triangles:v.renderer.info.render.triangles});}};requestAnimationFrame(sample);})`);
  await c.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await ev(`g.pause('inventory');ui.catalogue=true;ui.search='glider';ui.filter='All';ui.inspect='diamond_glider';ui.render()`);assert.ok(await ev("document.querySelector('.modal').getBoundingClientRect().right<=innerWidth"));await c.screenshot('horizon-mobile-catalogue');
  assert.equal(await ev('v.renderer.info.programs.filter(p=>p.diagnostics&&!p.diagnostics.runnable).length'),0);assert.deepEqual(c.errors,[]);assert.deepEqual(c.failed,[]);console.log('PASS: one versioned game instance, all six current unowned gliders discoverable, cotton equip/plant/grow/harvest, real pickaxe hold kills through flowers and drops pork, crafting/equipping/saving a glider, upgraded icons and tools, both terrain views and compact catalogue. '+JSON.stringify(timing));
}finally{c.socket.close();}
