import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';

const debugPort=process.env.VOXEL_CDP_PORT||9234,base=process.env.VOXEL_TEST_URL||'http://localhost:3002';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const {webSocketDebuggerUrl}=await(await fetch(`http://127.0.0.1:${debugPort}/json/version`)).json();
const ws=new WebSocket(webSocketDebuggerUrl),pending=new Map(),errors=[];
await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
let id=0;
ws.onmessage=({data})=>{const message=JSON.parse(data);if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);if(message.method==='Runtime.consoleAPICalled'&&message.params.type==='error')errors.push(message.params.args.map(arg=>arg.value||arg.description).join(' '));if(message.id){const call=pending.get(message.id);if(call){pending.delete(message.id);clearTimeout(call.timer);message.error?call.reject(Error(JSON.stringify(message.error))):call.resolve(message.result);}}};
const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const callId=++id,timer=setTimeout(()=>reject(Error(`Timeout: ${method}`)),30000);pending.set(callId,{resolve,reject,timer});ws.send(JSON.stringify({id:callId,method,params,sessionId}));});
const {browserContextId}=await send('Target.createBrowserContext');
try{
  const {targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});
  const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
  const call=(method,params={})=>send(method,params,sessionId);
  const evaluate=async expression=>{if(expression.trim().endsWith(';'))expression+='void 0';const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  const until=async(expression,label)=>{for(let count=0;count<160;count++){if(await evaluate(expression))return;await wait(100);}throw Error(label||expression);};
  await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});
  await call('Page.navigate',{url:base});
  await until(`!!document.querySelector('.block-lobby')`,'The game did not load.');
  await evaluate(`(async()=>{const m=await import(document.querySelector('script[type="module"]').src);window.g=m.game;window.r=m.renderer;window.ui=m.ui;window.settings=m.settings;})()`);
  await until('r.chunks.size>=9');

  await evaluate(`window.soloSeed=g.state.seed;window.soloPos={...g.pos};ui.action('parkour');window.p=g.parkour;`);
  await until(`g.state.mode==='parkour'&&document.querySelector('#loading').hidden&&r.queue.length===0`);
  assert.equal(await evaluate(`document.querySelector('#parkour-hud').hidden`),false);
  assert.equal(await evaluate(`getComputedStyle(document.querySelector('#survival')).display`),'none');
  const input=(code,pressed)=>call('Input.dispatchKeyEvent',{type:pressed?'keyDown':'keyUp',key:code==='Space'?' ':code==='ShiftLeft'?'Shift':code==='ControlLeft'?'Control':code.replace('Key','').toLowerCase(),code});
  await call('Page.bringToFront');
  await input('KeyW',true);await wait(350);await input('KeyW',false);
  assert.ok(await evaluate('p.timer.elapsed>0&&g.pos.z<5'), 'Real keyboard moves player and starts timer');
  await evaluate(`p.respawn();g.screen=null;ui.render();`);
  await input('ShiftLeft',true);await input('KeyW',true);await wait(200);
  assert.ok(await evaluate('g.sprinting&&Math.hypot(g.vx,g.vz)>6.8'),'Sprint accelerates');
  await input('KeyW',false);await input('ShiftLeft',false);await wait(180);
  await input('Space',true);await wait(110);
  assert.ok(await evaluate('g.pos.y>13.5&&!g.grounded'),'Jump raises player');
  await input('Space',false);await wait(900);
  assert.ok(await evaluate('g.grounded&&Math.abs(g.pos.y-13)<.02'),'Jump lands without clipping');
  await input('KeyC',true);await wait(100);assert.equal(await evaluate('g.crouching'),true);
  await input('KeyC',false);await wait(100);assert.equal(await evaluate('g.crouching'),false);
  await evaluate(`g.pos={...p.course.checkpoints[1]};g.grounded=true;g.velocity=0;`);
  await until('p.checkpoint===1');
  assert.ok(await evaluate('p.timer.splits.length===1'));
  await evaluate(`g.vx=4;g.velocity=-15;g.pos.y=3;`);
  await until('p.falls===1&&!p.respawnTime&&Math.abs(g.pos.y-14)<.1');
  assert.equal(await evaluate('g.vx===0&&g.vz===0&&g.velocity===0'),true);
  await input('KeyR',true);await input('KeyR',false);await until('p.falls===2&&!p.respawnTime');
  await evaluate(`g.pause();ui.render();window.pausedTime=p.timer.elapsed;`);await wait(250);
  assert.equal(await evaluate('p.timer.elapsed===pausedTime'),true);
  await evaluate(`ui.action('resume');`);
  for(let cp=2;cp<=4;cp++){
    await evaluate(`g.pos={...p.course.checkpoints[${cp}]};g.grounded=true;g.velocity=g.vx=g.vz=0;`);
    await until(`p.checkpoint===${cp}`);
  }
  await evaluate(`g.pos={...p.course.finish};g.grounded=true;g.velocity=0;`);
  await until(`g.screen==='parkour-results'`);
  assert.ok(await evaluate(`p.timer.finished&&p.best.time>0&&document.querySelector('.parkour-splits').children.length===4`));
  await writeFile('/private/tmp/voxel-vault-parkour-results.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
  await evaluate(`ui.action('parkour-restart');`);
  assert.equal(await evaluate('p.checkpoint===0&&p.timer.elapsed===0&&p.best.time>0'),true);
  await until('r.queue.length===0');
  await writeFile('/private/tmp/voxel-vault-parkour-play.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  await call('Emulation.setTouchEmulationEnabled',{enabled:true});
  await evaluate(`document.exitPointerLock();ui.touch=matchMedia('(pointer: coarse)').matches;`);await wait(150);await evaluate(`ui.resume();`);
  assert.equal(await evaluate(`document.querySelector('#touch-controls').hidden`),false);
  assert.ok(await evaluate('document.documentElement.scrollWidth<=innerWidth'));
  // Viewport emulation and pointer-lock release reach the compositor asynchronously.
  await until(`!document.pointerLockElement&&document.querySelector('#loading').hidden&&g.screen===null`);
  await evaluate(`new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))`);
  const dashPoint=await evaluate(`(()=>{const b=document.querySelector('[data-touch="dash"]').getBoundingClientRect();return {x:b.x+b.width/2,y:b.y+b.height/2};})()`);
  assert.equal(await evaluate(`document.elementFromPoint(${dashPoint.x},${dashPoint.y})?.dataset.touch`),'dash','Touch sprint must be reachable after mobile resize');
  await call('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[dashPoint]});
  await call('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});
  await evaluate(`g.touch.z=-1;`);await wait(200);
  assert.equal(await evaluate('g.sprinting'),true,JSON.stringify(await evaluate('({screen:g.screen,sprint:g.touchSprint,touch:g.touch,mode:settings.sprintMode,velocity:g.vz,locked:!!document.pointerLockElement,coarse:ui.touch})')));
  await evaluate(`g.touch.z=0;g.touchSprint=false;`);
  await writeFile('/private/tmp/voxel-vault-parkour-mobile.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
  await evaluate(`ui.action('menu');`);
  assert.equal(await evaluate('g.state.seed===soloSeed&&g.pos.x===soloPos.x&&g.pos.z===soloPos.z&&g.screen===\'menu\''),true,'Solo state restored');
  await evaluate(`ui.action('creative');g.pos={x:.5,y:7,z:20.5};g.world.edits.clear();g.state.selected=g.state.bar.indexOf('stone');if(g.state.selected<0){g.state.bar[0]='stone';g.state.selected=0;}g.target={x:0,y:6,z:19,type:'grass',normal:{x:0,y:1,z:0}};window.placed=g.place();`);
  assert.equal(await evaluate('placed&&g.world.get(0,7,19)===\'stone\''),true,'Existing block placement still works');
  await evaluate(`g.target={x:0,y:7,z:19,type:'stone',normal:{x:0,y:1,z:0}};g.mine(3);`);
  assert.equal(await evaluate('g.world.get(0,7,19)===null'),true,'Existing block mining still works');
  assert.deepEqual(errors,[],'Browser emitted errors.');
  console.log('PASS: actual keyboard walk/sprint/jump/crouch, checkpoint splits, fall and R respawn, pause timer, finish/PB/restart, mobile HUD, solo restoration, block placement/mining.');
}finally{await send('Target.disposeBrowserContext',{browserContextId});ws.close();}
