import assert from 'node:assert/strict';
import { writeFile } from 'node:fs/promises';

const debugPort=process.env.VOXEL_CDP_PORT||9234,base=process.env.VOXEL_TEST_URL||'http://localhost:3002';
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const {webSocketDebuggerUrl}=await(await fetch(`http://127.0.0.1:${debugPort}/json/version`)).json();
const ws=new WebSocket(webSocketDebuggerUrl),pending=new Map(),errors=[];
await new Promise((resolve,reject)=>{ws.onopen=resolve;ws.onerror=reject;});
let id=0;
ws.onmessage=({data})=>{const message=JSON.parse(data);if(message.method==='Runtime.exceptionThrown')errors.push(message.params.exceptionDetails);if(message.method==='Runtime.consoleAPICalled'&&message.params.type==='error')errors.push(message.params.args.map(arg=>arg.value||arg.description).join(' '));if(message.id){const call=pending.get(message.id);if(call){pending.delete(message.id);clearTimeout(call.timer);message.error?call.reject(Error(JSON.stringify(message.error))):call.resolve(message.result);}}};
const send=(method,params={},sessionId)=>new Promise((resolve,reject)=>{const callId=++id,timer=setTimeout(()=>reject(Error(`Timeout: ${method}`)),30000);pending.set(callId,{resolve,reject,timer});ws.send(JSON.stringify({id:callId,method,params,sessionId}));});
const {browserContextId}=await send('Target.createBrowserContext');
try{
  const {targetId}=await send('Target.createTarget',{url:'about:blank',browserContextId});
  const {sessionId}=await send('Target.attachToTarget',{targetId,flatten:true});
  const call=(method,params={})=>send(method,params,sessionId);
  const evaluate=async expression=>{const result=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,userGesture:true});if(result.exceptionDetails)throw Error(JSON.stringify(result.exceptionDetails));return result.result.value;};
  const until=async(expression,label)=>{for(let count=0;count<160;count++){if(await evaluate(expression))return;await wait(100);}throw Error(label||expression);};
  await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1280,height:800,deviceScaleFactor:1,mobile:false});
  await call('Page.navigate',{url:base});
  await until(`!!document.querySelector('.block-lobby')`,'The game did not load.');
  await evaluate(`(async()=>{const m=await import(document.querySelector('script[type="module"]').src);window.g=m.game;window.r=m.renderer;window.ui=m.ui;window.settings=m.settings;})()`);
  await until('r.chunks.size>=9');
  await evaluate(`Object.assign(settings,{quality:'custom',renderDistance:2,shadows:false,ambientOcclusion:false,particles:'high',antialias:true,fov:90,cameraEffects:true,debugFPS:true});r.applySettings(settings);g.screen=null;ui.render();`);
  await until('r.postProcess.target!==null&&r.queue.length===0&&!r.inflight&&r.ready.length===0','Terrain or antialiasing did not settle.');
  assert.equal(await evaluate('r.renderer.shadowMap.enabled'),false);
  assert.equal(await evaluate('r.options.renderDistance'),2);
  assert.equal(await evaluate('r.options.ambientOcclusion'),false);
  assert.equal(await evaluate('r.debugElement.hidden'),false);
  await evaluate(`window.geometryBefore=r.particles.mesh.geometry;window.bufferBefore=r.particles.mesh.instanceMatrix.array;const d=g.direction();for(let i=0;i<35;i++)r.burst(g.pos.x+d.x*3,g.pos.y+1.5,g.pos.z+d.z*3,'#ffca72',20);`);
  assert.equal(await evaluate('r.particles.count<=320&&r.particles.count>0'),true);
  await wait(120);
  assert.equal(await evaluate('r.particles.mesh.visible'),true);
  assert.equal(await evaluate('r.particles.mesh.geometry===geometryBefore&&r.particles.mesh.instanceMatrix.array===bufferBefore'),true);
  assert.equal(await evaluate('Number.isFinite(r.telemetry.fps)&&r.telemetry.drawCalls>0&&r.telemetry.triangles>0'),true);
  await writeFile('/private/tmp/voxel-vault-render-settings.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
  await evaluate(`settings.antialias=false;settings.particles='off';settings.cameraEffects=false;settings.bobbing=false;r.applySettings(settings);g.jumpImpulse=1;g.landingImpulse=1;`);
  await wait(200);
  assert.equal(await evaluate('r.postProcess.target===null&&r.particles.count===0'),true);
  assert.equal(await evaluate('r.cameraMotion.offset===0'),true);
  await evaluate(`settings.antialias=true;settings.ambientOcclusion=true;r.applySettings(settings);`);
  await until('r.postProcess.target!==null&&r.queue.length===0&&!r.inflight&&r.ready.length===0','AO rebuild did not settle.');
  await evaluate(`settings.renderDistance=6;settings.shadows=true;settings.particles='high';r.applySettings(settings);ui.action('parkour');`);
  await until(`g.state.dimension==='parkour'&&r.queue.length===0&&!r.inflight&&r.ready.length===0&&r.chunks.size>=9`,'Parkour terrain did not load through the worker.');
  assert.equal(await evaluate('r.hand.visible'),false);
  assert.equal(await evaluate('r.scenery.sky.visible&&r.scenery.clouds.visible'),true);
  assert.equal(await evaluate('[...r.chunks.values()].some(group=>group.children.some(mesh=>mesh.isInstancedMesh))'),false,'The cloud course should not generate terrain grass.');
  await writeFile('/private/tmp/voxel-vault-parkour-render.png',Buffer.from((await call('Page.captureScreenshot')).data,'base64'));
  const telemetry=await evaluate('r.telemetry');
  assert.deepEqual(errors,[],'Rendering emitted browser or shader errors.');
  console.log('Rendering browser checks passed:',JSON.stringify(telemetry));
}finally{await send('Target.disposeBrowserContext',{browserContextId});ws.close();}
