import assert from 'node:assert/strict';
import { connect,sleep } from './cdp.js';
const c=await connect(),{evaluate:ev,click}=c;
try{
 await c.send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await c.send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:5});await c.send('Page.reload');await sleep(1600);
 await ev(`(async()=>{const m=await import('/src/main.js');window.g=m.game;window.ui=m.ui;})()`);assert.equal(await ev('ui.touch'),true);await click('[data-action="play"]');assert.equal(await ev("document.querySelector('#touch-controls').hidden"),false);
 await ev('g.pos={x:.5,y:7,z:20.5};g.yaw=0;g.pitch=0');const before=await ev('g.pos.z');
 await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:85,y:655,id:1}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:85,y:625,id:1}]});await sleep(350);await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.ok(await ev('g.pos.z')<before-.3);assert.equal(await ev('g.touch.z'),0);
 const yaw=await ev('g.yaw');await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:260,y:360,id:2}]});await c.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:300,y:365,id:2}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.notEqual(await ev('g.yaw'),yaw);await ev(`g.hurtCooldown=0;g.state.hp=10;g.state.inv.potion=2`);const press=async selector=>{const p=await ev(`(()=>{const r=document.querySelector('${selector}').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);await c.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...p,id:7}]});await c.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});};await press('[data-touch=heal]');assert.equal(await ev('g.state.hp'),20);await press('[data-touch=dash]');assert.ok(await ev('g.dashCooldown')>0);await c.screenshot('touch-playing');
 await click('[data-action="inventory"]');assert.equal(await ev('g.screen'),'inventory');const active=await ev('document.activeElement.className');await c.send('Input.dispatchKeyEvent',{type:'keyDown',code:'Tab',key:'Tab'});await c.send('Input.dispatchKeyEvent',{type:'keyUp',code:'Tab',key:'Tab'});assert.equal(await ev('g.screen'),'inventory');assert.notEqual(await ev('document.activeElement.className'),active);await c.screenshot('touch-backpack');
 assert.deepEqual(c.errors,[]);console.log('PASS: real touch joystick, release cleanup, drag look, touch healing/dodge, backpack, and keyboard focus traversal.');
 await ev('g.pause();g.screen="menu";ui.render()');await c.send('Emulation.setTouchEmulationEnabled',{enabled:false});await c.send('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
}finally{c.socket.close();}
