import {infusionTooltip} from './infusion-ui.js?v=35';
import {potionFor} from './potions.js?v=35';
import { ITEMS } from './data.js?v=35';
import { icon } from './icons.js?v=35';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export function packSlot(g,name,count,extra=''){return `<button class="pack-slot ${(name===g.held?'selected ':'')+(g.state.infusions?.[name]?'infused':'')}" ${extra||(potionFor(name)?`data-drink="${name}"`:name==='firecracker'?'data-use-firecracker':`data-equip="${name}"`)} data-item="${name||''}" title="${esc((ITEMS[name]?.name||'Empty slot')+' · '+(ITEMS[name]?.description||'')+' '+infusionTooltip(g.state,name))}" aria-label="${esc(ITEMS[name]?.name||'Empty slot')}${count?' · '+count:''}">${name?icon(name,48):''}${count?`<b>${g.creative?'∞':count}</b>`:''}</button>`;}
export function inventoryLayout(g,items){
 const s=g.state;
 const slot=(name,count,extra='')=>packSlot(g,name,count,extra);
 const equipment=[...[['helm','Helm'],['chestplate','Chest'],['gauntlets','Hands'],['leggings','Legs'],['boots','Boots']].map(([key,label])=>[key,label,s.armorParts?.[key]]),['glider','Glider',s.glider],['ammo','Arrows',s.ammo]].map(([key,label,name])=>`<div class="pack-gear" data-gear="${key}"><small>${label}</small>${name?slot(name,0,ITEMS[name]?.slot?`data-unequip="${key}"`:null):`<div class="pack-slot vacant" aria-label="No ${label.toLowerCase()} equipped">—</div>`}</div>`).join('');
 const shirt=ITEMS[s.armorParts?.chestplate]?.color||'#397dba';
 let figure=`<svg viewBox="0 0 160 210" role="img" aria-label="Your character${s.armor?' wearing '+esc(ITEMS[s.armor].name):''}"><ellipse cx="80" cy="195" rx="45" ry="8" fill="#111c27"/><g stroke="#1b2534" stroke-width="2"><path fill="#34475f" d="M52 123h27v64H52zM81 123h27v64H81z"/><path fill="#252e3d" d="M50 180h29v13H50zM81 180h29v13H81z"/><path data-character-shirt fill="${shirt}" d="M50 65h60v65H50zM27 68h22v32H27zM111 68h22v32h-22z"/><path fill="#d9ae8c" d="M27 100h22v39H27zM111 100h22v39h-22zM56 22h48v46H56z"/><path fill="#47352f" d="M54 17h52v17H54z"/><path fill="#263444" d="M50 121h60v9H50z"/><path fill="#d7b467" d="M74 122h12v7H74z"/></g><path fill="#f5e9dc" d="M63 42h12v7H63zM85 42h12v7H85z"/><path fill="#304f66" d="M69 42h6v7h-6zM85 42h6v7h-6z"/></svg>`;
 const shapes={helm:'M51 16h58v20H51zM51 33h9v31h-9zM100 33h9v31h-9z',gauntlets:'M26 117h24v24H26zM110 117h24v24h-24z',leggings:'M52 130h27v49H52zM81 130h27v49H81z',boots:'M50 177h29v18H50zM81 177h29v18H81z'};
 figure=figure.replace('</svg>',Object.entries(shapes).map(([slot,d])=>`<path data-character-armor="${slot}" opacity="${s.armorParts?.[slot]?1:0}" d="${d}" fill="${ITEMS[s.armorParts?.[slot]]?.color||'#ffffff'}" stroke="#384940" stroke-width="2"/>`).join('')+'</svg>');
 const empty=Math.max(0,27-items.length);
 return `<section class="classic-pack"><div class="pack-top"><div class="pack-equipment">${equipment}</div><div class="pack-character">${figure}<small>EXPLORER</small></div><div class="pack-workshop"><h3>Crafting</h3><p>Make tools and supplies from your materials.</p><button data-action="craft" class="pack-craft">${icon('bench',40)} Open recipes →</button><button data-action="enchant" class="pack-craft">Aura ${s.aura||0} · Enchant gear</button><small>Select a hotbar slot, then choose an item. Click potions to drink instantly; use the catalogue to equip a bottle. Click equipped armor to remove it.</small></div></div><div class="pack-label">Backpack <span>${items.length} stacks</span></div><div class="pack-storage">${items.map(([k,n])=>slot(k,n)).join('')}${Array.from({length:empty},()=>'<div class="pack-slot vacant" aria-hidden="true"></div>').join('')}</div><div class="pack-label">Hotbar <span>Destination: slot ${s.selected+1}</span></div><div class="pack-hotbar">${s.bar.map((k,i)=>slot(k,s.inv[k]||0,`data-action="pack-slot-${i}" aria-pressed="${s.selected===i}"`)).join('')}</div></section>`;
}
