import { ITEMS } from './data.js?v=20';
import { icon } from './icons.js?v=20';
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
export function inventoryLayout(g,items){
 const s=g.state;
 const slot=(name,count,extra='')=>`<button class="pack-slot ${name===g.held?'selected':''}" ${extra||`data-equip="${name}"`} title="${esc(ITEMS[name]?.name||'Empty slot')}" aria-label="${esc(ITEMS[name]?.name||'Empty slot')}${count?' · '+count:''}">${name?icon(name,48):''}${count?`<b>${g.creative?'∞':count}</b>`:''}</button>`;
 const equipment=[['armor','Armor'],['glider','Glider'],['ammo','Arrows']].map(([key,label])=>`<div class="pack-gear"><small>${label}</small>${s[key]?slot(s[key],0):`<div class="pack-slot vacant" aria-label="No ${label.toLowerCase()} equipped">—</div>`}</div>`).join('');
 const shirt=ITEMS[s.armor]?.color||'#397dba';
 const figure=`<svg viewBox="0 0 160 210" role="img" aria-label="Your character${s.armor?' wearing '+esc(ITEMS[s.armor].name):''}"><ellipse cx="80" cy="195" rx="45" ry="8" fill="#111c27"/><g stroke="#1b2534" stroke-width="2"><path fill="#34475f" d="M52 123h27v64H52zM81 123h27v64H81z"/><path fill="#252e3d" d="M50 180h29v13H50zM81 180h29v13H81z"/><path fill="${shirt}" d="M50 65h60v65H50zM27 68h22v32H27zM111 68h22v32h-22z"/><path fill="#d9ae8c" d="M27 100h22v39H27zM111 100h22v39h-22zM56 22h48v46H56z"/><path fill="#47352f" d="M54 17h52v17H54z"/><path fill="#263444" d="M50 121h60v9H50z"/><path fill="#d7b467" d="M74 122h12v7H74z"/></g><path fill="#f5e9dc" d="M63 42h12v7H63zM85 42h12v7H85z"/><path fill="#304f66" d="M69 42h6v7h-6zM85 42h6v7h-6z"/></svg>`;
 const empty=Math.max(0,27-items.length);
 return `<section class="classic-pack"><div class="pack-top"><div class="pack-equipment">${equipment}</div><div class="pack-character">${figure}<small>EXPLORER</small></div><div class="pack-workshop"><h3>Crafting</h3><p>Make tools and supplies from your materials.</p><button data-action="craft" class="pack-craft">${icon('bench',40)} Open recipes →</button><small>Select a hotbar slot below, then choose an item to equip.</small></div></div><div class="pack-label">Backpack <span>${items.length} stacks</span></div><div class="pack-storage">${items.map(([k,n])=>slot(k,n)).join('')}${Array.from({length:empty},()=>'<div class="pack-slot vacant" aria-hidden="true"></div>').join('')}</div><div class="pack-label">Hotbar <span>Destination: slot ${s.selected+1}</span></div><div class="pack-hotbar">${s.bar.map((k,i)=>slot(k,s.inv[k]||0,`data-action="pack-slot-${i}" aria-pressed="${s.selected===i}"`)).join('')}</div></section>`;
}
