import { ITEMS, BLOCKS, RECIPES, BIOMES, SMELTING, canCraft, dailySeed } from './data.js';
import { loadState, saveSettings } from './save.js';
export function icon(name,size=36){
  const item=ITEMS[name]||{},c=item.color||'#a9c6aa';let shape='';
  if(item.kind==='sword')shape=`<path d="m24 4 4 4-13 16-5-5Z" fill="${c}"/><path d="m7 17 12 10-3 3L4 20Z" fill="#bc9a60"/><path d="m9 23 4 4-6 7-4-4Z" fill="#866346"/>`;
  else if(item.kind==='pickaxe'||item.kind==='axe')shape=`<path d="m9 31-4-3L22 6l4 3Z" fill="#9c7951"/><path d="${item.kind==='axe'?'m15 5 11 2 7 10-10 4-9-8Z':'m8 6 12-4 11 7 3 9-6-5-9-5-10 3Z'}" fill="${c}"/>`;
  else if(item.kind==='bow')shape='<path d="M10 3Q35 18 10 33" fill="none" stroke="#ba955f" stroke-width="4"/><path d="M10 3v30M4 18h26" stroke="#ecddbc" fill="none"/><path d="m27 15 5 3-5 3" fill="#ccd6c9"/>';
  else if(item.kind==='armor')shape=`<path d="m11 5 7 4 7-4 9 8-6 6-3-3v17H11V16l-3 3-6-6Z" fill="${c}"/><path d="M15 12h6v16h-6Z" fill="#ffffff30"/>`;
  else if(name==='apple')shape='<path d="M19 10Q6 5 5 19q0 14 13 14 13-1 13-14Q30 5 19 10" fill="#df8c6e"/><path d="M18 11V4q8-4 10 0-3 6-10 4" fill="#77a36a"/>';
  else if(name==='potion')shape='<path d="M14 3h8v10l8 10v9H6v-9l8-10Z" fill="#c5a5df"/><path d="M12 2h12v5H12Z" fill="#c3a273"/><path d="M9 24h18v5H9Z" fill="#ead0fa"/>';
  else if(name==='crystal')shape='<path d="m18 2 11 10-4 18-10 5-9-13 3-13Z" fill="#80cbbb"/><path d="m18 2 3 19-6 14L9 9Z" fill="#bff5df"/>';
  else if(name==='torch')shape='<path d="M15 16h6v18h-6Z" fill="#9c754b"/><path d="M10 6h16v15H10Z" fill="#e9bd65"/><path d="M14 9h8v9h-8Z" fill="#fff0bc"/>';
  else shape=`<path d="m3 10 15-8 15 8-15 8Z" fill="${c}"/><path d="M3 10v17l15 8V18Z" fill="${c}"/><path d="m18 18 15-8v17l-15 8Z" fill="${c}"/><path d="M3 10v17l15 8V18Z" fill="#00000018"/><path d="m18 18 15-8v17l-15 8Z" fill="#00000035"/>`;
  return `<svg width="${size}" height="${size}" viewBox="0 0 36 36" aria-hidden="true">${shape}</svg>`;
}
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const timeString=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
export class UI {
  constructor(game,settings){this.game=game;this.settings=settings;this.overlay=document.querySelector('#overlay');this.filter='All';this.tab='inventory';this.lastHud='';this.previousScreen=null;this.touch=matchMedia('(pointer: coarse)').matches;this.bind();this.render();}
  bind(){
    document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){this.action(b.dataset.action,b);return;}const smelt=e.target.closest('[data-smelt]');if(smelt){this.game.smelt(smelt.dataset.smelt);this.render();return;}const transfer=e.target.closest('[data-transfer]');if(transfer){this.game.transfer(transfer.dataset.transfer,transfer.dataset.withdraw==='true');this.render();return;}const craftButton=e.target.closest('[data-craft]');if(craftButton){this.game.craft(craftButton.dataset.craft);this.render();return;}const equip=e.target.closest('[data-equip]');if(equip){this.game.equip(equip.dataset.equip);this.render();return;}const filter=e.target.closest('[data-filter]');if(filter){this.filter=filter.dataset.filter;this.render();}const waypoint=e.target.closest('[data-waypoint]');if(waypoint){this.game.state.waypoint=waypoint.dataset.waypoint;this.game.save();this.render();}});
    document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const dialog=this.overlay.querySelector('[role=dialog]');if(!dialog)return;const controls=[...dialog.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')];if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
    document.addEventListener('input',e=>{const key=e.target.dataset.setting;if(!key)return;this.settings[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value;saveSettings(this.game.storage,this.settings);if(key==='quality'){this.game.renderer.renderer.setPixelRatio(Math.min(devicePixelRatio,this.settings.quality==='high'?1.75:1));this.game.renderer.center='';this.game.renderer.renderer.shadowMap.enabled=this.settings.quality==='high';}});
  }
  action(action,button){
    const g=this.game;g.audio.start();g.audio.play('click');
    if(action==='play'||action==='daily'||action==='creative'){g.start(action==='play'?'adventure':action);this.resume();}
    else if(action==='resume')this.resume();
    else if(action==='pause'){g.pause();this.render();}
    else if(['inventory','craft','map','journal'].includes(action)){g.pause(action);this.filter='All';this.render();}
    else if(action==='settings'||action==='help'){this.previousScreen=g.screen;g.screen=action;this.render();}
    else if(action==='back'){g.screen=this.previousScreen||'pause';this.previousScreen=null;this.render();}
    else if(action==='menu'){g.save();g.screen='menu';this.render();}
    else if(action==='respawn'){g.respawn();this.resume();}
    else if(action==='new'){g.screen='confirm';this.render();}
    else if(action==='confirm-new'){g.start('adventure',true);this.resume();}
    else if(action==='share'){
      const text=`Voxel Vault — ${g.state.mode==='daily'?'Daily '+g.state.seed:'World '+g.state.seed} · ${g.state.stats.built} blocks built · ${g.state.victory?'Guardian defeated':'Exploring'} · ${timeString(g.state.elapsed)}. The wilds await.`;
      if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(()=>g.toast('Adventure copied','Paste your result to share it.')).catch(()=>{this.shareText=text;g.screen='share';this.render();});else{this.shareText=text;g.screen='share';this.render();}
    }
    else if(action==='slot')g.select(Number(button.dataset.slot));
  }
  resume(){this.game.resume();this.render();if(!this.touch){const canvas=this.game.renderer.renderer.domElement;try{const promise=canvas.requestPointerLock();promise?.catch(()=>this.game.toast('Click the world to look around','If mouse capture is unavailable, drag to look.'));}catch{this.game.toast('Drag to look around','Mouse capture is unavailable in this browser.');}}}
  frame(title,kicker,body,wide=false){return `<section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${title}"><header><div><span class="eyebrow">${kicker}</span><h2>${title}</h2></div><button class="close" data-action="${this.game.screen==='death'?'respawn':['settings','help','share'].includes(this.game.screen)?'back':'resume'}" aria-label="Close">×</button></header>${body}</section>`;}
  render(){
    const g=this.game,s=g.state;document.body.dataset.screen=g.screen||'play';if(g.screen==='menu')document.querySelector('#toasts').replaceChildren();document.querySelector('#hud').hidden=!!g.screen;document.querySelector('#touch-controls').hidden=!!g.screen||!this.touch;this.overlay.className=g.screen==='menu'?'menu-overlay':g.screen?'modal-overlay':'';this.overlay.hidden=!g.screen;
    if(!g.screen){this.overlay.innerHTML='';this.hud();return;}
    if(g.screen==='menu'){
      const saved=loadState(g.storage,'adventure');
      this.overlay.innerHTML=`<div class="menu-top"><a class="brand" href="./"><span class="brand-cube">⬡</span> VOXEL VAULT</a><div class="menu-nav"><span class="edition">THE FRONTIER UPDATE <i>03</i></span><button data-action="settings" aria-label="Settings">⚙</button><button data-action="help" aria-label="How to play">?</button></div></div><div class="hero"><div class="eyebrow"><span class="tiny-line"></span> AN OPEN WORLD. MAKE IT YOUR OWN.</div><h1>VOXEL<br><span>VAULT</span><sup>✦</sup></h1><p>Mine deeper. Build bigger. Go farther.<br>Forests, rivers, mountains, and the world beneath them.</p><button class="primary play-button" data-action="play"><span>${saved?'Continue adventure':'Create your world'}</span><span>↗</span></button><div class="hero-sub">${saved?`Day ${Math.floor(saved.time/600)+1} · ${saved.stats.built} blocks placed · Saved on this device`:'Your world, your pace. No download needed.'}</div><div class="mode-buttons"><button data-action="daily"><span>☀</span><div>Daily world<small>A shared seed. A fresh start.</small></div><span>↗</span></button><button data-action="creative"><span>▧</span><div>Creative world<small>Every material. Room to build.</small></div><span>↗</span></button></div></div><div class="world-caption"><span class="caption-dot"></span><div>Somewhere in the Verdant Wilds<small>Every block is a possibility.</small></div></div><footer class="menu-footer"><div><span>01</span><strong>MAKE YOUR MARK</strong><small>Mine, craft & build</small></div><div><span>02</span><strong>FOLLOW THE UNKNOWN</strong><small>1,024 × 1,024 blocks</small></div><div><span>03</span><strong>BENEATH THE SURFACE</strong><small>Caves and ore veins to Y −64</small></div><button data-action="help">A field guide for the curious <span>↗</span></button></footer>`;
    }else if(g.screen==='pause')this.overlay.innerHTML=this.frame('Take a breath.','ADVENTURE PAUSED',`<p class="muted">The wilds will wait for you. Your world is saved on this device.</p><div class="pause-stats"><div><b>${s.stats.mined}</b><small>Blocks mined</small></div><div><b>${timeString(s.elapsed)}</b><small>Time exploring</small></div><div><b>${s.stats.built}</b><small>Blocks placed</small></div></div><button class="primary full" data-action="resume">Back to the wilds <span>↗</span></button><div class="button-grid"><button data-action="settings">Settings</button><button data-action="help">Field guide</button><button data-action="share">Share adventure</button><button data-action="menu">Save & main menu</button></div><button class="text-button" data-action="new">Start a new adventure world</button>`);
    else if(['inventory','craft','journal','map'].includes(g.screen))this.renderBook();
    else if(g.screen==='settings')this.overlay.innerHTML=this.frame('Make it yours.','SETTINGS',`<label class="setting">Sound volume<input type="range" min="0" max="1" step=".05" value="${this.settings.volume}" data-setting="volume"></label><label class="setting">Look sensitivity<input type="range" min=".3" max="2" step=".1" value="${this.settings.sensitivity}" data-setting="sensitivity"></label><label class="setting">Visual quality<select data-setting="quality"><option value="high" ${this.settings.quality==='high'?'selected':''}>High · detailed horizon</option><option value="low" ${this.settings.quality==='low'?'selected':''}>Performance · lighter rendering</option></select></label><label class="setting">Walking motion<input type="checkbox" data-setting="bobbing" ${this.settings.bobbing?'checked':''}></label><p class="muted">Changes save automatically. Turn off walking motion for a steadier camera.</p>`);
    else if(g.screen==='help')this.overlay.innerHTML=this.frame('Know your tools.','FIELD GUIDE',`<p>This is your world to shape. Collect logs, dig for stone, and make a furnace. Follow the hillside passage underground to find coal and metal veins. Smelt ore into ingots, craft better tools, and build wherever you like.</p><div class="controls-grid">${[['W A S D','Move'],['Mouse','Look'],['Space','Jump / swim / climb'],['Shift','Sprint'],['X','Crouch / descend'],['Left click','Attack / hold to mine'],['E / right click','Use item / place / interact'],['1–9 / wheel','Select hotbar'],['F / Q','Eat / heal'],['Tab / C','Backpack / crafting'],['M / J','Map / field notes'],['Z','Hold to zoom'],['B','Bridge block'],['Esc','Pause']].map(([k,v])=>`<div><kbd>${k}</kbd><span>${v}</span></div>`).join('')}</div><p class="muted">Hold Space for repeated jumps. Jumps keep your sprint momentum, and a brief grace period helps when leaving ledges. Ladders let you climb out of deep mines. Crouch to avoid walking off edges.</p><p class="muted">Place a furnace and interact to smelt. Place a chest to store items. Use a bed to set your spawn and rest until morning. Hold a lantern or place lights in caves. Creative flight: double tap Space, then Space to rise and X to descend.</p>`,true);
    else if(g.screen==='furnace')this.overlay.innerHTML=this.frame('Furnace.','SMELTING & BAKING',`<p class="muted">Each batch uses one ingredient and one fuel. Coal is used first, then timber.</p><div class="fuel-readout">${icon('coal',25)} Coal: ${s.inv.coal||0} &nbsp; Timber: ${s.inv.wood||0}</div><div class="recipe-grid">${SMELTING.map(r=>`<button class="recipe ${(s.inv[r.input]||0)>0&&(s.inv.coal||s.inv.wood)?'ready':''}" data-smelt="${r.output}" ${(s.inv[r.input]||0)>0&&(s.inv.coal||s.inv.wood)?'':'disabled'}>${icon(r.output,38)}<div><strong>${ITEMS[r.output].name} ×${r.count}</strong><small>${ITEMS[r.input].name}: ${s.inv[r.input]||0} available</small></div><span class="craft-label">SMELT →</span></button>`).join('')}</div>`,true);
    else if(g.screen==='storage'){const store=s.containers[g.containerKey]||{};this.overlay.innerHTML=this.frame('Storage chest.','KEEP YOUR MATERIALS',`<p class="muted">Select a stack to move up to 64 items between your backpack and this chest.</p><div class="storage-layout"><section><h3>Chest</h3><div class="storage-grid">${Object.entries(store).filter(([,n])=>n>0).map(([k,n])=>`<button data-transfer="${k}" data-withdraw="true">${icon(k,28)}<span>${ITEMS[k].name}</span><b>${n}</b></button>`).join('')||'<p class="muted">Nothing stored yet.</p>'}</div></section><section><h3>Backpack</h3><div class="storage-grid">${Object.entries(s.inv).filter(([,n])=>n>0).map(([k,n])=>`<button data-transfer="${k}">${icon(k,28)}<span>${ITEMS[k].name}</span><b>${n}</b></button>`).join('')}</div></section></div>`,true);}
    else if(g.screen==='death')this.overlay.innerHTML=this.frame('A story, interrupted.','YOU FELL IN THE WILDS',`<p>You’ll wake up at Wayfarer’s Rest with your gear and builds. Beds let you choose where you return.</p><button class="primary full" data-action="respawn">Return to camp <span>↗</span></button>`);
    else if(g.screen==='confirm')this.overlay.innerHTML=this.frame('A new beginning?','REPLACE ADVENTURE WORLD',`<p>This replaces your Adventure world’s terrain, inventory, and progress with a new seed. Daily and Creative saves stay separate.</p><button class="primary full" data-action="confirm-new">Create a new adventure</button><button class="full" data-action="resume">Keep my current world</button>`);
    else if(g.screen==='share')this.overlay.innerHTML=this.frame('A tale worth sharing.','YOUR ADVENTURE',`<p>Copy your result below:</p><textarea readonly rows="5">${escape(this.shareText)}</textarea>`);
    if(this.game.screen==='map')this.drawMap();this.overlay.querySelector('.close')?.focus({preventScroll:true});
  }
  renderBook(){
    const g=this.game,s=g.state,tabs=`<nav class="book-tabs">${[['inventory','Backpack'],['craft','Crafting'],['map','World map'],['journal','Journal']].map(([id,name])=>`<button class="${g.screen===id?'active':''}" data-action="${id}">${name}</button>`).join('')}</nav>`;let body='';
    if(g.screen==='inventory')body=`<div class="book-intro"><p>Everything you’ve picked up along the way.</p><span>Equip to hotbar slot <b>${s.selected+1}</b></span></div><div class="bag-grid">${Object.entries(s.inv).filter(([k,n])=>n>0&&ITEMS[k]).map(([k,n])=>`<button class="item-card ${g.held===k||s.armor===k?'equipped':''}" data-equip="${k}" title="${ITEMS[k].description||'Select to place this block.'}">${icon(k,42)}<strong>${ITEMS[k].name}</strong><span>${g.creative?'∞':'× '+n}</span>${g.held===k||s.armor===k?'<small>EQUIPPED</small>':''}</button>`).join('')}</div><div class="book-note">Click an item to equip it. Armor is worn automatically when selected. You keep your items if you fall.</div>`;
    if(g.screen==='craft')body=`<div class="book-intro"><p>A little resourcefulness goes a long way.</p></div><div class="filters">${['All','Gear','Supplies','Building'].map(f=>`<button class="${f===this.filter?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="recipe-grid">${RECIPES.filter(r=>this.filter==='All'||r.category===this.filter).map(r=>`<button class="recipe ${canCraft(s.inv,r)?'ready':''}" data-craft="${r.item}" ${canCraft(s.inv,r)?'':'disabled'}>${icon(r.item,44)}<div><strong>${ITEMS[r.item].name}${r.count?' ×'+r.count:''}</strong><small>${ITEMS[r.item].description||'Make something worth coming home to.'}</small><div class="costs">${Object.entries(r.cost).map(([k,n])=>`<span class="${(s.inv[k]||0)>=n?'enough':'missing'}">${s.inv[k]||0}/${n} ${ITEMS[k].name.replace(' deposit','').replace('Aether ','')}</span>`).join('')}</div></div><span class="craft-label">${canCraft(s.inv,r)?'CRAFT +':'NEED MATERIALS'}</span></button>`).join('')}</div>`;
    if(g.screen==='map')body=`<div class="map-layout"><div class="map-paper"><canvas id="map-canvas" width="600" height="600" aria-label="World map with your location and landmarks"></canvas><span class="map-north">N ↑</span><span class="map-label">THE KNOWN WILDS</span></div><div class="map-legend"><p>Choose a landmark to track on your compass.</p>${g.world.landmarks.map(l=>`<button class="${s.waypoint===l.id?'tracked':''}" data-waypoint="${l.id}"><i style="--color:${l.color}">◇</i><div><strong>${l.name}</strong><small>${l.subtitle}</small></div><span>${Math.round(Math.hypot(g.pos.x-l.x,g.pos.z-l.z))}m</span></button>`).join('')}<small class="muted">World ${s.seed} · ${s.mode==='daily'?'Daily world':'Your own corner of the wilds'}</small></div></div>`;
    if(g.screen==='journal')body=`<div class="journal-hero"><div><span class="eyebrow">A PLACE TO MAKE YOUR OWN</span><h3>Start small. Keep building.</h3><p>The terrain is open. There are no shrine requirements or campaign gates.</p></div></div><div class="journal-list">${[['01','Build a workshop','Collect logs and stone. Craft a workbench, furnace, chest and a bed. Use placed items with E.'],['02','Follow the rock layers','Coal and copper lie below the soil. Iron runs deeper; gold and diamond occur much farther underground. Bring a pickaxe and lights.'],['03','Make the trip back easier','Ladders climb mine shafts. Beds set your respawn point. A compass shows your way home. Your map covers the surrounding 640 blocks.'],['04','Choose your materials','Use oak, birch and pine planks, stone bricks, terracotta, polished granite, deepslate and glass. Furnaces turn ore, clay and sand into useful supplies.']].map(([n,title,text])=>`<div><span>${n}</span><section><h3>${title}</h3><p>${text}</p></section></div>`).join('')}</div><div class="book-note">A 1,024 × 1,024 world, extending from Y −64 to 95. Rivers have real water; caves beneath dry land stay dry. Your inventory and placed blocks save automatically.</div>`;
    this.overlay.innerHTML=this.frame('The wayfarer’s book.','YOUR ADVENTURE',tabs+body,true);
  }
  drawMap(){
    const canvas=document.querySelector('#map-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),g=this.game,span=640,scale=600/span,ox=g.pos.x-span/2,oz=g.pos.z-span/2;
    ctx.fillStyle='#7499ad';ctx.fillRect(0,0,600,600);
    for(let px=0;px<600;px+=6)for(let pz=0;pz<600;pz+=6){const x=Math.floor(ox+px/scale),z=Math.floor(oz+pz/scale),h=g.world.height(x,z);if(h<4)continue;ctx.fillStyle=BIOMES[g.world.biome(x,z)].color;ctx.fillRect(px,pz,6,6);if(h>32){ctx.fillStyle='#ffffff22';ctx.fillRect(px,pz,6,6);}}
    ctx.strokeStyle='#ece8d529';for(let a=0;a<600;a+=60){ctx.beginPath();ctx.moveTo(a,0);ctx.lineTo(a,600);ctx.moveTo(0,a);ctx.lineTo(600,a);ctx.stroke();}
    for(const l of g.world.landmarks){const x=(l.x-ox)*scale,z=(l.z-oz)*scale;ctx.fillStyle='#293e36';ctx.beginPath();ctx.arc(x,z,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f1e9ce';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(l.type==='camp'?'⌂':'•',x,z+4);}
    ctx.save();ctx.translate(300,300);ctx.rotate(-g.yaw);ctx.fillStyle='#fff2ba';ctx.strokeStyle='#253c33';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(8,9);ctx.lineTo(0,5);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
  }
  hud(){
    const g=this.game,s=g.state,b=BIOMES[g.world.biome(g.pos.x,g.pos.z)];const l=document.querySelector('#location');l.querySelector('strong').textContent=b.name;l.querySelector('small').textContent=`Day ${Math.floor(s.time/600)+1} · ${g.creative?'Creative mode':['Morning','Afternoon','Evening','Moonrise'][Math.floor(s.time%600/150)]}`;
    const quest=document.querySelector('#quest');quest.innerHTML=`<span class="eyebrow">YOUR WORLD</span><strong>${Math.floor(g.pos.x)}, ${Math.floor(g.pos.y)}, ${Math.floor(g.pos.z)}</strong><small>${s.stats.built} blocks placed · ${s.stats.mined} mined</small>`;
    document.querySelector('#hearts').innerHTML=Array.from({length:10},(_,i)=>`<i class="${s.hp>i*2?'filled':''}">♥</i>`).join('');document.querySelector('#armor').textContent=s.armor?'◈ '+(s.armor==='armor'?'35%':'55%'):'';document.querySelector('.stamina i').style.width=g.stamina+'%';
    const signature=JSON.stringify([s.bar,s.selected,s.bar.map(k=>s.inv[k]),g.creative]);if(signature!==this.lastHud){this.lastHud=signature;document.querySelector('#hotbar').innerHTML=s.bar.map((k,i)=>`<button class="slot ${i===s.selected?'selected':''}" data-action="slot" data-slot="${i}" title="${ITEMS[k].name}"><small>${i+1}</small>${icon(k)}<b>${g.creative?'∞':s.inv[k]||0}</b></button>`).join('');document.querySelector('#item-name').textContent=ITEMS[g.held].name;}
    const wp=g.world.landmarks.find(l=>l.id===s.waypoint)||g.world.landmarks[0];if(wp){let angle=Math.atan2(-(wp.x-g.pos.x),-(wp.z-g.pos.z))-g.yaw;angle=Math.atan2(Math.sin(angle),Math.cos(angle));document.querySelector('#compass').innerHTML=`<span>W</span><i></i><span>N</span><i></i><span>E</span><div class="waypoint" style="transform:translateX(${Math.max(-120,Math.min(120,-angle*80))}px)">◇<small>${Math.round(Math.hypot(wp.x-g.pos.x,wp.z-g.pos.z))}m · ${wp.name}</small></div>`;}
    const nearby=g.nearest(),interaction=document.querySelector('#interaction');interaction.hidden=!nearby;if(nearby)interaction.innerHTML=`<kbd>E</kbd> ${nearby.type==='supply'?'Open supplies':nearby.type==='camp'?'Rest':nearby.type==='furnace'?'Use furnace':nearby.type==='chest'?'Open storage':nearby.type==='bed'?'Sleep & set spawn':'Open crafting'}`;
    document.querySelector('#quick-guide').hidden=s.elapsed>100||g.creative;document.querySelector('#target').textContent=g.target?BLOCKS[g.target.type].name:'';document.querySelector('#mining').style.opacity=g.mineProgress>0?'1':'0';document.querySelector('#mining i').style.width=Math.min(100,g.mineProgress*100)+'%';
    document.querySelector('#boss').hidden=!g.boss;if(g.boss){document.querySelector('#boss-fill').style.width=g.boss.hp/g.boss.maxHp*100+'%';document.querySelector('#boss-phase').textContent=['','AWAKENED','ENRAGED','LAST STAND'][g.boss.phase||1];}
  }
  update(){
    for(const event of this.game.events.splice(0)){
      if(event.type==='toast'){if(this.game.screen==='menu')continue;const el=document.createElement('div');el.className='toast '+event.kind;el.innerHTML=`<span>${event.kind==='reward'?'✦':event.kind==='discovery'?'◇':'↗'}</span><div><strong>${escape(event.title)}</strong>${event.text?`<small>${escape(event.text)}</small>`:''}</div>`;const parent=document.querySelector('#toasts');parent.append(el);while(parent.children.length>(this.game.screen?1:3))parent.firstChild.remove();setTimeout(()=>el.remove(),4300);}
      if(event.type==='saved'){document.querySelector('#save-state').textContent=event.ok?'✓ World saved locally':'Could not save · storage unavailable';}
      if(event.type==='hurt'){const el=document.querySelector('#damage');el.classList.remove('hit');void el.offsetWidth;el.classList.add('hit');}
      if(event.type==='screen')this.render();
      if(event.type==='warning'){const el=document.querySelector('#combat-message');el.textContent=event.text;setTimeout(()=>el.textContent='',1300);}
      if(event.type==='damageNumber'){const el=document.createElement('span');el.className='damage-number';el.textContent=event.power;el.style.left=`${48+Math.random()*4}%`;el.style.top=`${42+Math.random()*4}%`;document.querySelector('#hud').append(el);setTimeout(()=>el.remove(),800);}
    }
    if(!this.game.screen)this.hud();
  }
}
