import { inventoryLayout } from './inventory-layout.js?v=22';
import { realmDestination } from './nether.js?v=22';
import { FORGE_OFFERS,OUTPOSTS } from './expeditions.js?v=22';
import { ITEMS, BLOCKS, RECIPES, BIOMES, SMELTING, CROPS, EFFECTS, canCraft, ingredientCount, dailySeed } from './data.js?v=22';
import { brandMark } from './brand.js?v=22';
import { ENEMIES } from './combat.js?v=22';
import { loadState, saveSettings } from './save.js?v=22';
import { icon } from './icons.js?v=22';
export { icon };
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const heldBow=g=>ITEMS[g.held]?.kind==='bow'&&g.attackCooldown>0;
const timeString=t=>`${Math.floor(t/60)}:${String(Math.floor(t%60)).padStart(2,'0')}`;
export class UI {
  constructor(game,settings){this.game=game;this.settings=settings;this.overlay=document.querySelector('#overlay');this.filter='All';this.search='';this.catalogue=false;this.inspect=null;this.tab='inventory';this.lastHud='';this.previousScreen=null;this.touch=matchMedia('(pointer: coarse)').matches;this.bind();this.render();}
  bind(){
    document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b){this.action(b.dataset.action,b);return;}const discover=e.target.closest('[data-discover]');if(discover){this.catalogue=true;this.filter=discover.dataset.discover==='glider'?'Gear':'All';this.search=discover.dataset.discover;this.inspect=null;this.game.pause('inventory');this.render();return;}const scope=e.target.closest('[data-scope]');if(scope){this.catalogue=scope.dataset.scope==='all';this.inspect=null;this.render();return;}const inspect=e.target.closest('[data-inspect]');if(inspect){this.inspect=inspect.dataset.inspect;this.render();return;}const recipe=e.target.closest('[data-recipe]');if(recipe){this.filter='All';this.search=ITEMS[recipe.dataset.recipe].name;this.game.pause('craft');this.render();return;}const forge=e.target.closest('[data-forge]');if(forge){this.game.forge(forge.dataset.forge);this.render();return;}const smelt=e.target.closest('[data-smelt]');if(smelt){this.game.smelt(smelt.dataset.smelt);this.render();return;}const transfer=e.target.closest('[data-transfer]');if(transfer){this.game.transfer(transfer.dataset.transfer,transfer.dataset.withdraw==='true');this.render();return;}const craftButton=e.target.closest('[data-craft]');if(craftButton){this.game.craft(craftButton.dataset.craft);this.render();return;}const equip=e.target.closest('[data-equip]');if(equip){this.game.equip(equip.dataset.equip);this.render();return;}const filter=e.target.closest('[data-filter]');if(filter){this.filter=filter.dataset.filter;this.render();}const waypoint=e.target.closest('[data-waypoint]');if(waypoint){this.game.state.waypoint=waypoint.dataset.waypoint;this.game.save();this.render();}});
    document.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const dialog=this.overlay.querySelector('[role=dialog]');if(!dialog)return;const controls=[...dialog.querySelectorAll('button:not(:disabled),input,select,textarea,a[href]')];if(!controls.length)return;const first=controls[0],last=controls.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});
    document.addEventListener('input',e=>{if(e.target.matches('[data-item-search]')){const cursor=e.target.selectionStart;this.search=e.target.value;this.renderBook();const input=this.overlay.querySelector('[data-item-search]');input?.focus();input?.setSelectionRange(cursor,cursor);return;}const key=e.target.dataset.setting;if(!key)return;this.settings[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value;saveSettings(this.game.storage,this.settings);if(key==='quality'){this.game.renderer.renderer.setPixelRatio(Math.min(devicePixelRatio,this.settings.quality==='high'?1.5:1));this.game.renderer.center='';this.game.renderer.renderer.shadowMap.enabled=this.settings.quality==='high';}});
  }
  action(action,button){
    const g=this.game;g.audio.start();g.audio.play('click');
    if(action.startsWith('pack-slot-')){g.select(Number(action.slice(10)));this.render();return;}
    if(action==='play'||action==='daily'||action==='creative'||action==='ender'){g.start(action==='play'||action==='ender'?'adventure':action);this.resume();}
    else if(action==='camera'){this.settings.perspective=((Number(this.settings.perspective)||0)+1)%3;saveSettings(g.storage,this.settings);g.toast(['First person','Third person · behind','Third person · front'][this.settings.perspective],'V / F5 to switch view');}
    else if(action==='return-world'){g.travel(realmDestination(g));this.resume();}
    else if(action==='rift-again'){g.restartRift();this.resume();}
    else if(action==='resume')this.resume();
    else if(action==='pause'){g.pause();this.render();}
    else if(['inventory','craft','map','journal'].includes(action)){g.pause(action);this.filter='All';this.search='';this.inspect=null;this.render();}
    else if(action==='settings'||action==='help'){this.previousScreen=g.screen;g.screen=action;this.render();}
    else if(action==='back'){g.screen=this.previousScreen||'pause';this.previousScreen=null;this.render();}
    else if(action==='menu'){g.save();g.screen='menu';this.render();}
    else if(action==='respawn'){g.respawn();this.resume();}
    else if(action==='new'){g.screen='confirm';this.render();}
    else if(action==='confirm-new'){g.start('adventure',true);this.resume();}
    else if(action==='share'){
      const text=`Voxel Vault — ${g.state.mode==='daily'?'Daily '+g.state.seed:'World '+g.state.seed} · ${g.state.stats.built} blocks built · ${g.state.victory?'Guardian defeated':'Exploring'} · ${timeString(g.state.elapsed)}. The wilds await.`;
      if(navigator.clipboard?.writeText)navigator.clipboard.writeText(text).then(()=>g.toast('Adventure copied','Paste your result to share it.')).catch(()=>{this.shareText=text;g.screen='share';this.render();});else{this.shareText=text;g.screen='share';this.render();}
    }
    else if(action==='slot')g.select(Number(button.dataset.slot));
  }
  resume(){this.game.resume();this.render();if(!this.touch){const canvas=this.game.renderer.renderer.domElement;try{const promise=canvas.requestPointerLock();promise?.catch(()=>this.game.toast('Click the world to look around','If mouse capture is unavailable, drag to look.'));}catch{this.game.toast('Drag to look around','Mouse capture is unavailable in this browser.');}}}
  frame(title,kicker,body,wide=false){return `<section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${title}"><header><div><span class="eyebrow">${kicker}</span><h2>${title}</h2></div><button class="close" data-action="${this.game.screen==='death'?'respawn':['settings','help','share'].includes(this.game.screen)?'back':'resume'}" aria-label="Close">×</button></header>${body}</section>`;}
  render(){
    const g=this.game,s=g.state;document.body.dataset.screen=g.screen||'play';if(g.screen==='menu')document.querySelector('#toasts').replaceChildren();document.querySelector('#hud').hidden=!!g.screen;document.querySelector('#touch-controls').hidden=!!g.screen||!this.touch;this.overlay.className=g.screen==='menu'?'menu-overlay':g.screen?'modal-overlay':'';this.overlay.hidden=!g.screen;
    if(!g.screen){this.overlay.innerHTML='';this.hud();return;}
    if(g.screen==='menu'){
      const saved=loadState(g.storage,'adventure');
      this.overlay.innerHTML=`<div class="lobby-top"><a class="brand" href="./">${brandMark()} VOXEL VAULT</a><span>Single player · Saved on this device</span><button data-action="settings" aria-label="Settings">⚙ Settings</button><button data-action="help">How to play</button></div><section class="block-lobby"><div class="lobby-logo">voxel<span>vault</span><small>BUILD. EXPLORE. PLAY.</small></div><div class="lobby-heading"><h1>Your next adventure starts here.</h1><span>BUILD · SOAR · DISCOVER</span></div><div class="game-modes"><button class="game-mode survival-mode" data-action="play"><div class="mode-art"><span class="mode-tag">${saved?'CONTINUE':'EXPLORE & BUILD'}</span><div class="block-scene"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="mode-info"><h2>Adventure</h2><p>Find the glowing portal. Overworld → Nether → Ender.</p><strong>${saved?'Continue playing':'Play now'} <span>▶</span></strong></div></button><button class="game-mode creative-mode" data-action="creative"><div class="mode-art"><span class="mode-tag">UNLIMITED BLOCKS</span><div class="block-scene"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="mode-info"><h2>Creative</h2><p>Fly, pick any block, and build anything.</p><strong>Play now <span>▶</span></strong></div></button><button class="game-mode daily-mode" data-action="daily"><div class="mode-art"><span class="mode-tag">NEW SEED EVERY DAY</span><div class="block-scene"><i></i><i></i><i></i><i></i><i></i><i></i></div></div><div class="mode-info"><h2>Daily World</h2><p>A fresh world to discover each day.</p><strong>Play now <span>▶</span></strong></div></button></div><button class="ender-world-button" data-action="ender"><span class="ender-symbol">◈</span><span><b>Dragon Isles</b><small>Fight the Ender Dragon · Fly the Rift Run · Bring your trophy home</small></span><strong>Begin the journey ▶</strong></button><div class="lobby-tip"><b>TIP</b> V / F5 switches camera views. Hold Space to jump. Right click to place blocks.</div><p class="lobby-save">${saved?`Your Survival world is ready · Day ${Math.floor(saved.time/600)+1} · ${saved.stats.built} blocks placed`:'Your worlds save automatically in this browser.'}</p></section>`;
    }else if(g.screen==='pause')this.overlay.innerHTML=this.frame('Paused','SURVIVAL WORLD',`<p class="muted">The wilds will wait for you. Your world is saved on this device.</p><div class="pause-stats"><div><b>${s.stats.mined}</b><small>Blocks mined</small></div><div><b>${timeString(s.elapsed)}</b><small>Time exploring</small></div><div><b>${s.stats.built}</b><small>Blocks placed</small></div></div><button class="primary full" data-action="resume">Resume game <span>▶</span></button><div class="button-grid"><button data-action="settings">Settings</button><button data-action="help">Field guide</button><button data-action="share">Share adventure</button><button data-action="menu">Save & main menu</button></div>${s.dimension==='ender'?'<button class="full" data-action="return-world">Return to the Nether</button>':''}<button class="text-button" data-action="new">Start a new adventure world</button>`);
    else if(['inventory','craft','journal','map'].includes(g.screen))this.renderBook();
    else if(g.screen==='settings')this.overlay.innerHTML=this.frame('Make it yours.','SETTINGS',`<label class="setting">Camera view<select data-setting="perspective">${['First person','Third person · behind','Third person · front'].map((label,i)=>`<option value="${i}" ${Number(this.settings.perspective)===i?'selected':''}>${label}</option>`).join('')}</select></label><label class="setting">Sound volume<input type="range" min="0" max="1" step=".05" value="${this.settings.volume}" data-setting="volume"></label><label class="setting">Look sensitivity<input type="range" min=".3" max="2" step=".1" value="${this.settings.sensitivity}" data-setting="sensitivity"></label><label class="setting">Visual quality<select data-setting="quality"><option value="high" ${this.settings.quality==='high'?'selected':''}>High · detailed horizon</option><option value="low" ${this.settings.quality==='low'?'selected':''}>Performance · lighter rendering</option></select></label><label class="setting">Walking motion<input type="checkbox" data-setting="bobbing" ${this.settings.bobbing?'checked':''}></label><p class="muted">Changes save automatically. Turn off walking motion for a steadier camera.</p>`);
    else if(g.screen==='help')this.overlay.innerHTML=this.frame('Know your tools.','FIELD GUIDE',`<p>This is your world to shape. Collect logs, dig for stone, and make a furnace. Find the hillside passage on your map, or dig your own way to coal and metal veins. Smelt ore into ingots, craft better tools, and build wherever you like.</p><div class="controls-grid">${[['W A S D','Move'],['Mouse','Look'],['V / F5','Switch camera perspective'],['Space','Jump / swim / climb'],['Shift','Sprint'],['X','Crouch / descend'],['Left click','Attack / mine / draw bow'],['E / right click','Use item / place / interact'],['1–9 / wheel','Select hotbar'],['F / Q','Eat food / drink tonic'],['G','Open / close equipped glider'],['Tab / C','Backpack / crafting'],['M / J','Map / field notes'],['Z','Hold to zoom'],['B','Bridge block'],['T','Rotate stairs'],['Esc','Pause']].map(([k,v])=>`<div><kbd>${k}</kbd><span>${v}</span></div>`).join('')}</div><p class="muted">Hold Space for repeated jumps. Jumps keep your sprint momentum, and a brief grace period helps when leaving ledges. Ladders let you climb out of deep mines. Crouch to avoid walking off edges, or to place blocks against chests and furnaces. Hold right click or E to place continuously. T rotates stairs; matching slabs stack into a full block.</p><p class="muted">Place a furnace and interact to smelt. Place a chest to store items. Use a bed to set your spawn and rest until morning. Use a hoe on clear grass or earth, then plant seeds, carrots or potatoes. There are nine crops; water within four blocks speeds planting growth by 25%. Harvest mature plants with E. Hunt deer, pigs, cows, sheep, chickens and rabbits for raw meat. Craft a furnace to cook meat; campfires roast mushrooms and bake bread. Food refills hunger and stores energy for gradual healing. Special meals grant timed effects. Hold attack with a longbow or recurve bow, then release to shoot. Equip a glider in the backpack, jump from a height and press G. Look down to dive; look up to descend slowly. Hold a lantern or place lights in caves. Creative flight: double tap Space, then Space to rise and X to descend.</p>`,true);
    else if(g.screen==='forge')this.overlay.innerHTML=this.frame('Relic Forge','TURN EXPLORATION INTO EQUIPMENT',`<p class="muted">Diamonds are the forge currency. Earn them by mining deep ore, exploring outposts and completing Rift challenges.</p><div class="forge-balance">${icon('diamond',34)} <strong>${s.inv.diamond||0}</strong> diamonds</div><div class="recipe-grid">${FORGE_OFFERS.map(([name,cost])=>{const ready=(s.inv.diamond||0)>=cost;return `<button class="recipe ${ready?'ready':''}" data-forge="${name}" ${ready?'':'disabled'}>${icon(name,54)}<div><strong>${ITEMS[name].name}</strong><small>${ITEMS[name].description}</small></div><span>${cost} diamonds</span></button>`}).join('')}</div>`,true);
    else if(g.screen==='furnace')this.overlay.innerHTML=this.frame(g.station?.type==='campfire'?'Campfire.':'Furnace.',g.station?.type==='campfire'?'CAMPFIRE COOKING':'SMELTING & BAKING',`<p class="muted">${g.station?.type==='campfire'?'Campfires burn timber. Coal is reserved for furnaces.':'Each batch uses one ingredient and one coal or timber. Coal is used first.'}</p><div class="fuel-readout">${icon('coal',25)} Coal: ${s.inv.coal||0} &nbsp; Timber: ${ingredientCount(s.inv,'wood')}</div><div class="recipe-grid">${SMELTING.filter(r=>g.station?.type!=='campfire'||ITEMS[r.output].kind==='food'&&!r.furnaceOnly).map(r=>`<button class="recipe ${(s.inv[r.input]||0)>0&&((g.station?.type!=='campfire'&&s.inv.coal)||ingredientCount(s.inv,'wood'))?'ready':''}" data-smelt="${r.output}" ${(s.inv[r.input]||0)>0&&((g.station?.type!=='campfire'&&s.inv.coal)||ingredientCount(s.inv,'wood'))?'':'disabled'}>${icon(r.output,38)}<div><strong>${ITEMS[r.output].name} ×${r.count}</strong><small>${ITEMS[r.input].name}: ${s.inv[r.input]||0} available</small></div><span class="craft-label">SMELT →</span></button>`).join('')}</div>`,true);
    else if(g.screen==='storage'){const store=g.containerKey==='moon'?s.moonChest:s.containers[g.containerKey]||{};this.overlay.innerHTML=this.frame('Storage chest.','KEEP YOUR MATERIALS',`<p class="muted">Select a stack to move up to 64 items between your backpack and this chest.</p><div class="storage-layout"><section><h3>Chest</h3><div class="storage-grid">${Object.entries(store).filter(([,n])=>n>0).map(([k,n])=>`<button data-transfer="${k}" data-withdraw="true">${icon(k,28)}<span>${ITEMS[k].name}</span><b>${n}</b></button>`).join('')||'<p class="muted">Nothing stored yet.</p>'}</div></section><section><h3>Backpack</h3><div class="storage-grid">${Object.entries(s.inv).filter(([,n])=>n>0).map(([k,n])=>`<button data-transfer="${k}">${icon(k,28)}<span>${ITEMS[k].name}</span><b>${n}</b></button>`).join('')}</div></section></div>`,true);}
    else if(g.screen==='death')this.overlay.innerHTML=this.frame('A story, interrupted.','YOU FELL IN THE WILDS',`<p>You’ll return to your starting clearing or last bed with your gear and builds.</p><button class="primary full" data-action="respawn">Return home <span>↗</span></button>`);
    else if(g.screen==='confirm')this.overlay.innerHTML=this.frame('A new beginning?','REPLACE ADVENTURE WORLD',`<p>This replaces your Adventure world’s terrain, inventory, and progress with a new seed and a safe random starting location. Daily and Creative saves stay separate.</p><button class="primary full" data-action="confirm-new">Create a new adventure</button><button class="full" data-action="resume">Keep my current world</button>`);
    else if(g.screen==='share')this.overlay.innerHTML=this.frame('A tale worth sharing.','YOUR ADVENTURE',`<p>Copy your result below:</p><textarea readonly rows="5">${escape(this.shareText)}</textarea>`);
    if(this.game.screen==='map')this.drawMap();this.overlay.querySelector('.close')?.focus({preventScroll:true});
  }
  renderBook(){
    const g=this.game,s=g.state,tabs=`<nav class="book-tabs">${[['inventory','Backpack'],['craft','Crafting'],['map','World map'],['journal','Journal']].map(([id,name])=>`<button class="${g.screen===id?'active':''}" data-action="${id}">${name}</button>`).join('')}</nav>`;let body='';
    const searchField=`<label class="item-search"><span>⌕</span><input data-item-search type="search" placeholder="Search items, tools, materials…" aria-label="Search items" value="${escape(this.search)}" autocomplete="off"></label>`;
    const matches=k=>!this.search||`${ITEMS[k].name} ${ITEMS[k].description||''}`.toLowerCase().includes(this.search.toLowerCase());
    const itemGroup=k=>{const i=ITEMS[k];return i.kind==='food'?'Food':i.plant||i.kind==='seed'?'Nature':i.place?'Building':i.kind==='material'?'Materials':'Gear';};
    if(g.screen==='inventory'){
      const items=Object.keys(ITEMS).map(k=>[k,s.inv[k]||0]).filter(([k,n])=>(this.catalogue||n>0)&&!ITEMS[k].hidden&&matches(k)&&(this.filter==='All'||itemGroup(k)===this.filter));
      body=`<div class="book-intro"><p>${g.creative?'Your complete material library. Select an item to start building.':'Your tools, harvests, and everything worth keeping.'}</p><span>Equip to slot <b>${s.selected+1}</b></span></div>${searchField}<div class="catalogue-controls"><div><button data-scope="owned" class="${!this.catalogue?'active':''}">In backpack</button><button data-scope="all" class="${this.catalogue?'active':''}">All ${Object.values(ITEMS).filter(i=>!i.hidden).length} items</button></div><div><button data-discover="glider">△ Gliders</button><button data-discover="cotton">♧ Cotton</button></div></div>${this.itemDetails()}<div class="filters inventory-filters">${['All','Gear','Building','Materials','Food','Nature'].map(f=>`<button class="${f===this.filter?'active':''}" data-filter="${f}">${f}</button>`).join('')}<small>${items.length} items</small></div><div class="bag-grid">${items.map(([k,n])=>`<button class="item-card ${n===0?'unowned':''} ${g.held===k||s.armor===k||s.glider===k||s.ammo===k?'equipped':''}" ${this.catalogue?'data-inspect':'data-equip'}="${k}" title="${escape((ITEMS[k].description||'Equip to place this material.')+(ITEMS[k].nutrition?` Food +${ITEMS[k].nutrition} · energy +${ITEMS[k].saturation}.`:''))}" style="--item-color:${ITEMS[k].color}"><div class="item-art">${icon(k,48)}</div><strong>${ITEMS[k].name}</strong><span>${g.creative?'∞':n?'× '+n:'NOT OWNED'}</span><small>${g.held===k||s.armor===k||s.glider===k||s.ammo===k?'EQUIPPED':ITEMS[k].kind==='glider'?ITEMS[k].glideSpeed+' M/S · DESCENT '+ITEMS[k].sink:ITEMS[k].tier?'TIER '+ITEMS[k].tier:ITEMS[k].nutrition?'FOOD +'+ITEMS[k].nutrition+' · ENERGY +'+ITEMS[k].saturation:itemGroup(k).toUpperCase()}</small></button>`).join('')||'<p class="empty-items">No items match. Try another search or category.</p>'}</div><div class="book-note">Select to equip. Gliders, armor and arrows use separate equipment slots. Food replenishes hunger and stores energy; special meals also grant timed effects.</div>`;
    }
    if(g.screen==='inventory'&&!this.catalogue){const owned=Object.entries(s.inv).filter(([k,n])=>n>0&&ITEMS[k]&&!ITEMS[k].hidden&&matches(k));body=searchField+`<div class="catalogue-controls"><button data-scope="all">Browse all items</button></div>`+inventoryLayout(g,owned);}
    const atBench=g.screen==='craft'&&g.nearbyWorkbench(),ready=r=>canCraft(s.inv,r)&&(r.station!=='bench'||atBench);
    if(g.screen==='craft')body=`<div class="book-intro"><p>${atBench?'Crafting table in range — all recipes available.':'Hand crafting — place a workbench nearby for advanced recipes. Workbench: 6 timber.'}</p></div>${searchField}<div class="filters">${['All','Gear','Supplies','Building'].map(f=>`<button class="${f===this.filter?'active':''}" data-filter="${f}">${f}</button>`).join('')}</div><div class="craft-shortcuts"><button data-discover="glider">Browse gliders</button><button data-discover="cotton">Cotton & cloth</button></div><div class="recipe-grid">${RECIPES.filter(r=>matches(r.item)&&(this.filter==='All'||r.category===this.filter)).map(r=>`<button class="recipe ${ready(r)?'ready':''}" data-craft="${r.item}" ${ready(r)?'':'disabled'}>${icon(r.item,44)}<div><strong>${ITEMS[r.item].name}${r.count?' ×'+r.count:''}</strong><small>${r.station==='bench'?'Crafting table required':'Craft by hand'} · ${ITEMS[r.item].description||'Building material'}</small><div class="costs">${Object.entries(r.cost).map(([k,n])=>`<span class="${ingredientCount(s.inv,k,r)>=n?'enough':'missing'}">${ingredientCount(s.inv,k,r)}/${n} ${ITEMS[k].name.replace(' deposit','').replace('Aether ','')}</span>`).join('')}</div></div><span class="craft-label">${ready(r)?'CRAFT +':r.station==='bench'&&!atBench?'NEEDS TABLE':'NEED MATERIALS'}</span></button>`).join('')}</div>`;
    if(g.screen==='map')body=`<div class="map-layout"><div class="map-paper"><canvas id="map-canvas" width="600" height="600" aria-label="World map with your location and landmarks"></canvas><span class="map-north">N ↑</span><span class="map-label">THE KNOWN WILDS</span></div><div class="map-legend"><p>Choose a landmark to track on your compass.</p>${g.world.landmarks.map(l=>`<button class="${s.waypoint===l.id?'tracked':''}" data-waypoint="${l.id}"><i style="--color:${l.color}">◇</i><div><strong>${l.name}</strong><small>${l.subtitle}</small></div><span>${Math.round(Math.hypot(g.pos.x-l.x,g.pos.z-l.z))}m</span></button>`).join('')}<small class="muted">World ${s.seed} · ${s.mode==='daily'?'Daily world':'Your own corner of the wilds'}</small></div></div>`;
    if(g.screen==='journal')body=`<div class="journal-hero"><div><span class="eyebrow">A PLACE TO MAKE YOUR OWN</span><h3>Start small. Keep building.</h3><p>Travel from the Overworld to the Nether. Find the Ashen Fortress portal to reach the Ender.</p></div></div><div class="journal-list">${[['01','Build a workshop','Collect logs and stone. Craft a workbench, furnace, chest and a bed. Use placed items with E.'],['02','Follow the rock layers','Coal and iron lie below the soil. Gold and diamond occur farther underground. Moonstone is found in the Ender. Bring a pickaxe and lights.'],['03','Make the trip back easier','Ladders climb mine shafts. Beds set your respawn point. A compass shows your way home. New worlds start in a random clearing. Home tracks your starting point until you use a bed. Your map covers the surrounding 640 blocks.'],['04','Plant something that lasts','Grow wheat, carrots, cotton, watermelons, melons, potatoes, tomatoes, corn and berries. Plant seeds or root vegetables in garden soil. Nearby water reduces growth time by 25%. Harvest with E. Cotton makes cloth for gliders; cane makes sugar.'],['05','Hunt and cook','Six animal species roam suitable biomes. Deer yield venison; pigs yield pork, cows beef, sheep mutton, chickens poultry and rabbits rabbit meat. Walk over drops to collect them. Cook raw meat in a crafted furnace with timber or coal. Food stores energy for gradual healing.'],['06','Pack for the journey','Special meals grant speed, higher jumps, invisibility, ore sight, haste, night vision or featherfall. Effect timers pause with the game and survive saves. Attacking reveals you briefly while invisible.'],['07','Take to the skies','Craft a cloth and timber glider, then upgrade it with iron, gold, diamond or moonstone. Equip it in your backpack. Press G while airborne; look down to dive or up for a shallower descent. Gold favors speed; diamond and moonstone descend more slowly.'],['08','Choose your materials','Use oak, birch and pine planks, stone bricks, terracotta, polished granite, deepslate marble, metal panels, fabric and glass. Furnaces turn ore, clay and sand into useful supplies.']].map(([n,title,text])=>`<div><span>${n}</span><section><h3>${title}</h3><p>${text}</p></section></div>`).join('')}</div><div class="book-note">A 1,024 × 1,024 world, extending from Y −64 to 95. Rivers have real water; caves beneath dry land stay dry. Your inventory and placed blocks save automatically.</div>`;
    this.overlay.innerHTML=this.frame(g.screen==='inventory'?'Inventory':'The wayfarer’s book.','YOUR ADVENTURE',tabs+body,true);
  }
  itemDetails(){
    const name=this.inspect,item=ITEMS[name];if(!item||!this.catalogue)return '';
    const count=this.game.state.inv[name]||0,recipe=RECIPES.find(r=>r.item===name),crop=Object.entries(CROPS).find(([,c])=>c.seed===name||Object.hasOwn(c.loot,name));
    const source=recipe?'Craft this item with the ingredients shown in its recipe.':crop?`Grow ${crop[0]} in garden soil or harvest its ripe wild plants. Cotton seeds are included in the starting backpack.`:item.description||'Gather this material in the world.';
    return `<section class="item-detail">${icon(name,64)}<div><strong>${item.name}</strong><p>${item.description||source}</p>${recipe?'':`<small>${source}</small>`}<div>${count?`<button data-equip="${name}">Equip · ${count} owned</button>`:''}${recipe?`<button data-recipe="${name}">Show crafting recipe →</button>`:''}</div></div></section>`;
  }
  drawMap(){
    const canvas=document.querySelector('#map-canvas');if(!canvas)return;const ctx=canvas.getContext('2d'),g=this.game,span=640,scale=600/span,ox=g.pos.x-span/2,oz=g.pos.z-span/2;
    ctx.fillStyle=g.state.dimension==='ender'?'#30243f':'#7499ad';ctx.fillRect(0,0,600,600);
    for(let px=0;px<600;px+=6)for(let pz=0;pz<600;pz+=6){const x=Math.floor(ox+px/scale),z=Math.floor(oz+pz/scale),h=g.world.height(x,z);if(h<4)continue;ctx.fillStyle=BIOMES[g.world.biome(x,z)].color;ctx.fillRect(px,pz,6,6);if(h>32){ctx.fillStyle='#ffffff22';ctx.fillRect(px,pz,6,6);}}
    ctx.strokeStyle='#ece8d529';for(let a=0;a<600;a+=60){ctx.beginPath();ctx.moveTo(a,0);ctx.lineTo(a,600);ctx.moveTo(0,a);ctx.lineTo(600,a);ctx.stroke();}
    for(const l of g.world.landmarks){const x=(l.x-ox)*scale,z=(l.z-oz)*scale;ctx.fillStyle='#293e36';ctx.beginPath();ctx.arc(x,z,8,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f1e9ce';ctx.font='12px system-ui';ctx.textAlign='center';ctx.fillText(l.type==='camp'?'⌂':'•',x,z+4);}
    ctx.save();ctx.translate(300,300);ctx.rotate(-g.yaw);ctx.fillStyle='#fff2ba';ctx.strokeStyle='#253c33';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-11);ctx.lineTo(8,9);ctx.lineTo(0,5);ctx.lineTo(-8,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();
  }
  hud(){
    const g=this.game,s=g.state,b=BIOMES[g.world.biome(g.pos.x,g.pos.z)];const l=document.querySelector('#location');l.querySelector('.eyebrow').textContent=s.dimension==='nether'?'NETHER WORLD':s.dimension==='ender'?'ENDER WORLD':g.creative?'CREATIVE WORLD':s.mode==='daily'?'DAILY WORLD':'SURVIVAL WORLD';l.querySelector('strong').textContent=b.name;l.querySelector('small').textContent=`Day ${Math.floor(s.time/600)+1} · ${g.creative?'Creative mode':['Morning','Afternoon','Evening','Moonrise'][Math.floor(s.time%600/150)]}`;
    const quest=document.querySelector('#quest');quest.innerHTML=`<span class="eyebrow">YOUR WORLD</span><strong>${Math.floor(g.pos.x)}, ${Math.floor(g.pos.y)}, ${Math.floor(g.pos.z)}</strong><small>${s.stats.built} built · ${s.stats.mined} mined · ${s.stats.harvested} harvested</small>`;
    const rift=s.rift,challenge=document.querySelector('#rift-objective');
    if(challenge){challenge.hidden=!!g.screen;const end=s.dimension==='ender',count=rift.collected.length,time=Math.max(0,(rift.finished||s.elapsed)-rift.started);challenge.innerHTML=end?`<span class="rift-kicker">${count===3?'EXPEDITION COMPLETE':'THE RIFT RUN'}</span><strong>${count===3?'Rift materials earned!':'Activate the three anchors'}</strong><div class="anchor-dots">${['dawn','ember','dusk'].map((id,i)=>`<span class="${rift.collected.includes(id)?'done':''}">${rift.collected.includes(id)?'✓':i+1}</span>`).join('')}<b>${timeString(time)}</b></div><small>${count===3?'Return through the portal. Your gear comes with you.':'Cyan pads launch you. Steer with the mouse. Press G to close your glider and land.'}</small>${count===3?'<button data-action="rift-again">Run again →</button>':''}`:`<span class="rift-kicker">${rift.rewarded?'RIFT RUN CONQUERED':'A WORLD BEYOND YOUR WORLD'}</span><strong>${rift.rewarded?'Build with your new rewards':'Explore the outposts'}</strong><small>${rift.rewarded?'Your moonstone gear works here too.':`${s.opened.filter(id=>id.startsWith('outpost-')).length}/3 treasures found. Follow map markers. Mine diamonds for forge gear, then explore the Rift.`}</small>`;}
    document.querySelector('#hearts').innerHTML=`<span class="hp-fill" style="width:${Math.max(0,Math.min(100,s.hp*5))}%"></span><b>${Math.max(0,Math.ceil(s.hp*5))} / 100</b>`;document.querySelector('#hearts').setAttribute('aria-label',`Health ${Math.max(0,Math.ceil(s.hp*5))} out of 100`);document.querySelector('#armor').textContent=s.armor?'◈ '+Math.round((ITEMS[s.armor]?.reduction||0)*100)+'%':'';document.querySelector('.stamina i').style.width=g.stamina+'%';
    if(challenge&&s.dimension==='nether')challenge.innerHTML='<span class="rift-kicker">OVERWORLD → NETHER → ENDER</span><strong>Find the Ashen Fortress</strong><small>Follow the fortress marker. Defeat the fortress guardian to unseal its Ender portal. The arrival portal leads home.</small>';
    if(challenge&&s.dimension==='ender'){
      if(g.boss?.kind==='dragon')challenge.innerHTML=`<span class="rift-kicker">ENDER DRAGON</span><strong>${{circle:'Aim for the dragon',breath:'Keep moving!',swoop:'Dodge the swoop',perch:'Landed — use your sword'}[g.boss.stage]}</strong><small>${g.boss.crystals??4}/4 healing crystals remain. Shoot the crystals on the four pillars. Step back when a slam is marked.</small>`;
      else challenge.innerHTML+=`<small class="dragon-invitation">${s.dragon.defeated?'Dragon defeated. Your trophy travels home with you.':'Dragon challenge: find the altar at 0, −7 on this island. Press E to awaken it. Bring your own bow, arrows, armor and glider.'}</small>`;
    }
    document.querySelector('#food-label').textContent=`Food ${Math.ceil(s.food)}/20`;
    document.querySelector('#food-fill').style.width=s.food*5+'%';document.querySelector('#reserve-fill').style.width=s.saturation*5+'%';
    document.querySelector('#reserve-label').textContent=`Energy ${Math.ceil(s.saturation)}`;
    document.querySelector('.food-row').classList.toggle('hungry',s.food<6);
    document.querySelector('#active-effects').innerHTML=Object.entries(s.effects).map(([name,t])=>`<span style="--effect-color:${EFFECTS[name].color}"><i></i>${EFFECTS[name].name}<b>${timeString(Math.ceil(t))}</b></span>`).join('');
    const flight=document.querySelector('#flight-status');flight.textContent=s.glider?(g.gliding?`${ITEMS[s.glider].name} · ${Math.round(Math.hypot(g.vx,g.vz))} m/s · G to close`:`△ ${ITEMS[s.glider].name} · G in the air`):'';
    document.querySelector('[data-touch="glide"]').hidden=!s.glider;
    const progress=document.querySelector('#action-progress'),draw=g.drawState,cross=heldBow(g),eating=g.eating;
    progress.hidden=!eating&&!draw&&!cross&&g.mineProgress<=0;
    if(!progress.hidden){progress.querySelector('span').textContent=g.mineProgress>0?'Mining '+(BLOCKS[g.target?.type]?.name||'block')+' · '+Math.floor(g.mineProgress*100)+'%':eating?'Eating '+ITEMS[eating.item].name:draw?'Draw · release to shoot':`Reloading · ${g.attackCooldown.toFixed(1)}s`;progress.querySelector('i').style.width=Math.min(100,100*(g.mineProgress>0?g.mineProgress:eating?1-eating.time/eating.total:draw?draw.time/ITEMS[g.held].drawTime:1-g.attackCooldown/(ITEMS[g.held].cooldown||.45)))+'%';}
    const signature=JSON.stringify([s.bar,s.selected,s.bar.map(k=>s.inv[k]),g.creative]);if(signature!==this.lastHud){this.lastHud=signature;document.querySelector('#hotbar').innerHTML=s.bar.map((k,i)=>`<button class="slot ${i===s.selected?'selected':''}" data-action="slot" data-slot="${i}" title="${ITEMS[k].name}"><small>${i+1}</small>${icon(k)}<b>${g.creative?'∞':s.inv[k]||0}</b></button>`).join('');document.querySelector('#item-name').textContent=ITEMS[g.held].name;}
    const wp=g.world.landmarks.find(l=>l.id===s.waypoint)||g.world.landmarks.at(-1);if(wp){let angle=Math.atan2(-(wp.x-g.pos.x),-(wp.z-g.pos.z))-g.yaw;angle=Math.atan2(Math.sin(angle),Math.cos(angle));document.querySelector('#compass').innerHTML=`<span>W</span><i></i><span>N</span><i></i><span>E</span><div class="waypoint" style="transform:translateX(${Math.max(-120,Math.min(120,-angle*80))}px)">◇<small>${Math.round(Math.hypot(wp.x-g.pos.x,wp.z-g.pos.z))}m · ${wp.name}</small></div>`;}
    const nearby=g.nearest(),interaction=document.querySelector('#interaction'),held=ITEMS[g.held],target=g.target;
    const contextual=held.kind==='hoe'&&['grass','dirt'].includes(target?.type)?'Prepare garden soil':held.crop&&target?.type==='farmland'?'Plant '+held.crop:null;
    const labels={relic_forge:'Open Relic Forge',anchor:'Activate '+(nearby?.name||'anchor'),ender_gate:'Travel to '+realmDestination(g,nearby),moonstone_chest:'Open shared moonstone storage',supply:'Open supplies',camp:'Rest',furnace:'Use furnace',campfire:'Cook over fire',chest:'Open storage',bed:'Sleep & set spawn',wheat_crop:'Harvest wheat',carrot_crop:'Harvest carrots'};
    labels.dragon_altar=nearby?.name;
    interaction.hidden=!nearby&&!contextual;if(!interaction.hidden)interaction.innerHTML=`<kbd>E</kbd> ${contextual||labels[nearby?.type]||(Object.values(CROPS).some(c=>c.mature===nearby?.type)?'Harvest '+BLOCKS[nearby.type].name:'Open crafting')}`;
    const buildHint=document.querySelector('#build-hint');buildHint.textContent=g.preview?(g.preview.valid?(ITEMS[g.held].shape==='stairs'?'T · Rotate stairs   E / right click · Place':'Hold E / right click · Place'):(g.preview.reason||'')):'';
    document.querySelector('#quick-guide').hidden=s.elapsed>100||g.creative;const growing=g.target&&s.crops[`${g.target.x},${g.target.y},${g.target.z}`];document.querySelector('#target').textContent=g.mobTarget?`${ENEMIES[g.mobTarget.mob.kind].name} · ${Math.ceil(g.mobTarget.mob.hp)}/${g.mobTarget.mob.maxHp} ♥ · ${g.mobTarget.distance<=4?'Left click to hit':'Move closer'}`:g.target?BLOCKS[g.target.type].name+(growing?` · ${Math.max(0,Math.ceil(growing.readyAt-s.elapsed))}s to harvest`:''):'';document.querySelector('#mining').style.opacity=g.mineProgress>0?'1':'0';document.querySelector('#mining i').style.width=Math.min(100,g.mineProgress*100)+'%';
    document.querySelector('#boss').hidden=!g.boss;if(g.boss){document.querySelector('#boss>div>span').textContent=ENEMIES[g.boss.kind].name.toUpperCase();document.querySelector('#boss-fill').style.width=g.boss.hp/g.boss.maxHp*100+'%';document.querySelector('#boss-phase').textContent=g.boss.kind==='dragon'?`${Math.ceil(g.boss.hp)} / ${g.boss.maxHp} · ${g.boss.phase===2?'ENRAGED':'AWAKENED'}`:['','AWAKENED','ENRAGED','LAST STAND'][g.boss.phase||1];}
  }
  update(){
    for(const event of this.game.events.splice(0)){
      if(event.type==='dragonDefeated'){const el=document.querySelector('#combat-message');el.classList.add('rift-victory');el.innerHTML='<small>THE ISLANDS ARE YOURS</small>DRAGON DEFEATED<small>Take your Dragon Egg home through the portal</small>';setTimeout(()=>{el.classList.remove('rift-victory');el.textContent='';},5500);}
      if(event.type==='toast'){if(this.game.screen==='menu')continue;const el=document.createElement('div');el.className='toast '+event.kind;el.innerHTML=`<span>${event.kind==='reward'?'✦':event.kind==='discovery'?'◇':'↗'}</span><div><strong>${escape(event.title)}</strong>${event.text?`<small>${escape(event.text)}</small>`:''}</div>`;const parent=document.querySelector('#toasts');parent.append(el);while(parent.children.length>(this.game.screen?1:3))parent.firstChild.remove();setTimeout(()=>el.remove(),4300);}
      if(event.type==='pickup'){const el=document.createElement('div');el.className='pickup';el.innerHTML=`${icon(event.item,25)}<span>${ITEMS[event.item]?.name||event.item}</span><b>+${event.count}</b>`;const list=document.querySelector('#pickups');list.append(el);while(list.children.length>4)list.firstChild.remove();setTimeout(()=>el.remove(),2200);}
      if(event.type==='saved'){document.querySelector('#save-state').textContent=event.ok?'✓ World saved locally':'Could not save · storage unavailable';}
      if(event.type==='hurt'){const el=document.querySelector('#damage');el.classList.remove('hit');void el.offsetWidth;el.classList.add('hit');}
      if(event.type==='browse'){this.catalogue=true;this.inspect=null;this.filter=event.search==='glider'?'Gear':'All';this.search=event.search;this.render();}
      if(event.type==='screen')this.render();
      if(event.type==='riftComplete'){const el=document.querySelector('#combat-message');el.classList.add('rift-victory');el.innerHTML='<small>ALL THREE ANCHORS ACTIVATED</small>RIFT RUN COMPLETE<small>Moonstone Sword · Moonstone Armor · Moonstone Glider</small>';setTimeout(()=>{el.classList.remove('rift-victory');el.textContent='';},5500);}
      if(event.type==='warning'){const el=document.querySelector('#combat-message');el.textContent=event.text;setTimeout(()=>el.textContent='',1300);}
      if(event.type==='damageNumber'){const el=document.createElement('span');el.className='damage-number';el.textContent=event.power;const point=this.game.renderer.screenPoint(event.mob.x,event.mob.y+(ENEMIES[event.mob.kind]?.height||1.7),event.mob.z);if(!point)continue;el.style.left=`${point.x*100}%`;el.style.top=`${point.y*100}%`;document.querySelector('#hud').append(el);setTimeout(()=>el.remove(),800);}
    }
    if(!this.game.screen)this.hud();
  }
}
